---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: Create a new directory named New-Dir
      path: ~/New-Dir
      state: directory

    - name: Create a file named new-file
      path: ~/New-Dir/new-file
      state: touch

    - name: Change time zone to Africa/lagos
      timezone:
        name: Africa/lagos

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
